version: '3'

services:
  external_source_ds:
    build:
      context: ./EXTERNAL_SOURCE_DATA_STORE
    networks:
      - my_network

  features_store:
    build:
      context: ./FEATURES_STORE
    networks:
      - my_network

  data_management:
    build:
      context: ./DATA_MANAGEMENT_PIPELINE
    networks:
      - my_network

  model_store:
    build:
      context: ./MODEL_STORE
    networks:
      - my_network

  model_management:
    build:
      context: ./MODEL_MANAGEMENT_PIPELINE
    networks:
      - my_network

  webapp:
    build:
      context: ./WEB_APP
    networks:
      - my_network

  prometheus:
    image: prom/prometheus:v2.14.0
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - my_network
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    depends_on:
      - webapp

  grafana:
    image: grafana/grafana:7.5.0 
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=pass
    networks:
      - my_network
    depends_on:
      - prometheus
    ports:
      - '8080:3000'

networks:
  my_network:
