apiVersion: v1
kind: Pod
metadata:
  name: pod-mlops
spec:
  containers:
    - name: external-source-ds
      image: mlops-on-kubernates-external_source_ds 

    - name: features-store
      image: mlops-on-kubernates-features_store  

    - name: data-management
      image: mlops-on-kubernates-data_management

    - name: model-store
      image: mlops-on-kubernates-model_store
      
    - name: model-management
      image: mlops-on-kubernates-model_management 

    - name: webapp
      image: mlops-on-kubernates-webapp