apiVersion: batch/v1
kind: CronJob
metadata:
  name: app2-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: app2-container
            image: app2
          restartPolicy: OnFailure
